const MACHINE_QUERY_KEY = "machines";
const CATEGORIES_QUERY_KEY = "categories";
const CONTACT_QUERY_KEY = "contacts";
const MANUFACTURER_INFO_QUERY_KEY = "manufacturerInfo";

export { MACHINE_QUERY_KEY, CATEGORIES_QUERY_KEY, CONTACT_QUERY_KEY, MANUFACTURER_INFO_QUERY_KEY }