import type { Metadata } from "next";
import { Google_Sans_Flex } from "next/font/google";
import "@/app/globals.css";

const GoogleSansFlex = Google_Sans_Flex({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Admin | SP Mech Group",
  description: "Generated by create next app",
};

import { LenisProvider } from "@/providers/LenisProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GoogleSansFlex.className} bg-background antialiased`}
      >
        <QueryProvider>
          <LenisProvider>
            <TooltipProvider>{children}</TooltipProvider>
            <Toaster
              position="top-center"
              duration={3000}
              toastOptions={
                {
                  cancelButtonStyle: {
                    backgroundColor: "white"
                  },
                  actionButtonStyle: {
                    backgroundColor: "white"
                  }
                }
              }
              richColors />
          </LenisProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
